checks:
    php:
        code_rating: true
        duplication: true
        
filter:
    excluded_paths: [tests/*]

tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.

build:
    nodes:
        analysis:
            tests:
                override:
                - php-scrutinizer-run